
import type { Suggestion } from './types';
import type { ValidateDocumentOutput, Finding } from '@/ai/flows/validate-document';

const findings: Finding[] = [
  {
    nombre_archivo_normativa: "Reglamento de Contrataciones, Art. 1422",
    nombre_archivo_documento: "3118772 SERV RECAMBIO UPS 96 FJS (1)",
    tipo: 'Irregularidad',
    titulo_incidencia: "Justificación de urgencia insuficiente",
    articulo_o_seccion: "Art. 1422",
    pagina: '1',
    gravedad: 'Alta',
    evidencia: "Se solicita con carácter de URGENTE la adquisición e instalación de un (1) sistema de aire acondicionado de precisión y un (1) equipo UPS para el centro de datos principal de la Entidad.",
    propuesta_procedimiento: "Para dar cumplimiento al Art. 1422 del Reglamento de Contrataciones, se debe fundamentar la urgencia adjuntando un informe técnico que detalle el estado crítico de los equipos y el riesgo inminente para la continuidad del servicio. La simple mención 'URGENTE' es insuficiente y puede viciar el procedimiento.",
    justificacion_legal: "El Art. 1422 del Reglamento de Contrataciones exige que las razones de urgencia 'deberán fundarse fehacientemente'. La simple mención de la palabra 'URGENTE' sin pruebas documentales es insuficiente y puede llevar al rechazo del procedimiento.",
    justificacion_tecnica: "Aporta la evidencia necesaria para que los organismos de control y la autoridad competente puedan validar la procedencia de un trámite acelerado, si correspondiera.",
    consecuencia_estimada: "Nulidad de la justificación de urgencia, responsabilidad del funcionario solicitante, retrasos significativos en la contratación.",
  },
  {
    nombre_archivo_normativa: "Leyes de Contrataciones, Art. 26",
    nombre_archivo_documento: "3118772 SERV RECAMBIO UPS 96 FJS (1)",
    tipo: 'Irregularidad',
    titulo_incidencia: "Contradicción entre urgencia y procedimiento",
    articulo_o_seccion: "Art. 26",
    pagina: '1',
    gravedad: 'Alta',
    evidencia: "El presente trámite se sustanciará bajo la modalidad de Licitación Pública.",
    propuesta_procedimiento: "Existe una contradicción entre la urgencia invocada y la modalidad de Licitación Pública. Se debe optar por una de las siguientes vías: a) Tramitar como Contratación Directa por Urgencia, o b) Eliminar la mención 'URGENTE' y proceder como Licitación Pública regular para evitar vicios de procedimiento.",
    justificacion_legal: "Existe una contradicción insalvable entre tramitar una Licitación Pública con plazos y pasos regulares, y declarar una urgencia no fundamentada. Esto crea inseguridad jurídica y vicia el procedimiento.",
    justificacion_tecnica: "La coherencia del documento es clave para la correcta interpretación por parte de los oferentes y fiscalizadores. Procedimientos contradictorios generan confusión.",
    consecuencia_estimada: "Nulidad del proceso por vicios de procedimiento, rechazo por parte de los organismos de control.",
  },
  {
    nombre_archivo_normativa: "Reglamento de Contrataciones, Art. 150",
    nombre_archivo_documento: "3118772 SERV RECAMBIO UPS 96 FJS (1)",
    tipo: 'Mejora de Redacción',
    titulo_incidencia: "Fundamentación débil para cotización en USD",
    articulo_o_seccion: "Art. 150",
    pagina: '1',
    gravedad: 'Baja',
    evidencia: "Se solicita que la contratación se realice en dólares estadounidenses por el origen de los productos que se intenta adquirir y para garantizar la mayor cantidad de ofertas.",
    propuesta_redaccion: "Para robustecer la justificación de cotizar en moneda extranjera, se sugiere añadir: '...conforme a un informe de mercado que se adjunta, el cual demuestra que los bienes a adquirir, por su origen, son exclusiva o mayoritariamente cotizados en dicha moneda, a fin de garantizar la mayor concurrencia de ofertas.'",
    justificacion_legal: "Si bien la normativa permite cotizar en moneda extranjera con justificación, la solidez de dicha justificación es clave para evitar observaciones de los organismos de control sobre la transparencia y conveniencia económica.",
    justificacion_tecnica: "Un informe de mercado proporciona evidencia objetiva que respalda la decisión administrativa y protege al proceso de futuros cuestionamientos.",
    consecuencia_estimada: "Observaciones menores de auditoría por falta de evidencia que respalde la decisión.",
  },
  {
    nombre_archivo_normativa: "Ley de Contrataciones, Art. 11",
    nombre_archivo_documento: "3118772 SERV RECAMBIO UPS 96 FJS (1)",
    tipo: 'Irregularidad',
    titulo_incidencia: "Potencial direccionamiento y falta de imparcialidad",
    articulo_o_seccion: "Art. 11",
    pagina: '1',
    gravedad: 'Alta',
    evidencia: "Se adjunta como referencia el presupuesto N° 1234 de la firma EXCELCOM S.A. por un total de USD 50.000.",
    propuesta_procedimiento: "Para garantizar la imparcialidad y libre competencia, se debe reemplazar el presupuesto de un proveedor específico por un Presupuesto Oficial desglosado y anónimo, elaborado por la Entidad, que sirva de base para la comparación de ofertas, conforme al Art. 11 de la Ley de Contrataciones.",
    justificacion_legal: "El Art. 11 de la Ley de Contrataciones prohíbe la inclusión de especificaciones que direccionen la contratación hacia un oferente particular. Incluir un presupuesto de una firma específica vulnera los principios de imparcialidad y libre concurrencia.",
    justificacion_tecnica: "Asegura que el proceso sea competitivo y que la evaluación se base en las capacidades técnicas y económicas de todos los oferentes, no en la propuesta de uno solo.",
    consecuencia_estimada: "Riesgo de impugnaciones, anulación del proceso por favorecer a un oferente, y cuestionamientos de los organismos de control.",
  },
  {
    nombre_archivo_normativa: "Reglamento de Contrataciones, Art. 1422",
    nombre_archivo_documento: "3118772 SERV RECAMBIO UPS 96 FJS (1)",
    tipo: 'Mejora de Redacción',
    titulo_incidencia: "Incongruencia entre urgencia y plazo de ejecución",
    articulo_o_seccion: "Art. 1422",
    pagina: '1',
    gravedad: 'Media',
    evidencia: "El plazo máximo para la entrega e instalación será de ciento veinte (120) días.",
    propuesta_redaccion: "PLAZO DE EJECUCIÓN: El plazo máximo para la entrega e instalación de los equipos será de treinta (30) días corridos a partir de la firma del contrato.",
    justificacion_legal: "El Art. 1422 del Reglamento de Contrataciones, que regula la urgencia, presupone plazos de ejecución acordes. Un plazo de 120 días debilita la justificación para cualquier tratamiento preferencial o procedimiento de excepción.",
    justificacion_tecnica: "Aclara las expectativas reales del plazo de entrega y asegura la coherencia interna del documento, evitando confusiones a los oferentes y fiscalizadores.",
    consecuencia_estimada: "Debilitamiento de la justificación de urgencia, posibles observaciones de los organismos de control por inconsistencias en el pliego.",
  },
];


export const upsMockData: Partial<ValidateDocumentOutput> = {
  documentTitle: "Evaluación 3118772 SERV RECAMBIO UPS 96 FJS (1)",
  isRelevantDocument: true,
  relevancyReasoning: "",
  findings: findings,
  complianceScore: 35,
  legalRiskScore: 65,
  scoringBreakdown: {
    totalFindings: 5,
    criticalFindings: 3,
    totalPenalty: 65,
    penaltiesByGravity: {
      Alta: { count: 3, penalty: 45 },
      Media: { count: 1, penalty: 15 },
      Baja: { count: 1, penalty: 5 },
    },
  },
  riskCategory: {
    category: 'VERY_HIGH',
    label: 'Muy Alto',
    color: 'red',
    description: 'El documento tiene problemas críticos que requieren corrección inmediata.',
  },
};
