
import type { DocumentBlock, Suggestion, SuggestionCategory, SuggestionSeverity } from './types';
import type { ValidateDocumentOutput, Finding } from '@/ai/flows/validate-document';

const findings: Finding[] = [
  {
    nombre_archivo_normativa: "Ley 80 de 1993, Art. 3",
    nombre_archivo_documento: "Evaluación Pliego XYZ-2025",
    tipo: 'Mejora de Redacción',
    titulo_incidencia: "Omisión de Cláusula de Actualización",
    articulo_o_seccion: 'Art. 3',
    pagina: '1',
    gravedad: 'Alta',
    evidencia: "Este contrato busca cubrir todas las necesidades de software de la organización.",
    propuesta_redaccion: "Se recomienda incluir la siguiente cláusula en el objeto para evitar costos no planificados: 'El proveedor garantizará la actualización a nuevas versiones del software cubierto por este contrato sin costo adicional para la Entidad durante toda la vigencia del servicio de soporte técnico.'",
    justificacion_legal: "No prever las actualizaciones futuras va en contra de los principios de economía y eficiencia, pues puede generar costos adicionales no planificados para la entidad.",
    justificacion_tecnica: "Garantiza que la entidad se mantenga actualizada tecnológicamente y optimiza la inversión.",
    consecuencia_estimada: "Posibles costos adicionales no presupuestados para actualizaciones.",
  },
  {
    nombre_archivo_normativa: "Ley 80 de 1993, Art. 24",
    nombre_archivo_documento: "Evaluación Pliego XYZ-2025",
    tipo: 'Mejora de Redacción',
    titulo_incidencia: "Ambigüedad en el Objeto",
    articulo_o_seccion: "Art. 24",
    pagina: '1',
    gravedad: 'Baja',
    evidencia: "OBJETO: El objeto del presente proceso de contratación es la adquisición de licencias de software para la entidad, así como el soporte técnico especializado durante un periodo de 12 meses.",
    propuesta_redaccion: "Para mayor claridad, se sugiere reestructurar el objeto del contrato de la siguiente manera: 'El presente contrato tiene por objeto: 1. La adquisición de [CANTIDAD] licencias de [TIPO DE SOFTWARE]. 2. La prestación de soporte técnico especializado para dichas licencias por un período de 12 meses, conforme a los niveles de servicio detallados en el Anexo I.'",
    justificacion_legal: "La redacción ambigua y poco estructurada del objeto contractual dificulta la comprensión clara por parte de los proponentes, lo que atenta contra el principio de transparencia.",
    justificacion_tecnica: "Facilita la comprensión por parte de los proponentes y reduce el riesgo de interpretaciones erróneas.",
    consecuencia_estimada: "Consultas recurrentes, posibles protestas o impugnaciones.",
  },
  {
    nombre_archivo_normativa: "Ley 1150 de 2007, Art. 5",
    nombre_archivo_documento: "Evaluación Pliego XYZ-2025",
    tipo: 'Irregularidad',
    titulo_incidencia: "Criterios de habilitación subjetivos",
    articulo_o_seccion: "Art. 5",
    pagina: '2',
    gravedad: 'Alta',
    evidencia: "Se requiere experiencia previa en contratos con el estado. El personal técnico debe estar certificado.",
    propuesta_procedimiento: "Para garantizar la objetividad, se debe especificar qué se considera 'experiencia previa' (ej: 'acreditar al menos dos contratos de similar naturaleza y monto en los últimos tres años') y qué 'certificaciones' son requeridas para el personal técnico (ej: 'Certificación oficial del fabricante en la versión X del software').",
    justificacion_legal: "La ley exige que los criterios de evaluación sean objetivos, claros y completos. El texto original no desagrega los criterios técnicos, lo que podría dar lugar a una evaluación subjetiva.",
    justificacion_tecnica: "Permite una evaluación transparente y equitativa de las ofertas.",
    consecuencia_estimada: "Riesgo de selección no objetiva, posibles demandas.",
  },
  {
    nombre_archivo_normativa: "Ley 1150 de 2007, Art. 5",
    nombre_archivo_documento: "Evaluación Pliego XYZ-2025",
    tipo: 'Irregularidad',
    titulo_incidencia: "Falta de detalle en criterios",
    articulo_o_seccion: "Art. 5",
    pagina: '3',
    gravedad: 'Media',
    evidencia: "La calidad se medirá según la propuesta técnica.",
    propuesta_procedimiento: "Para evitar subjetividad, la 'Calidad Técnica' debe desagregarse. Propuesta: a) Metodología (15 pts), b) Cumplimiento de especificaciones avanzadas (10 pts), c) Plan de capacitación (5 pts). La 'Innovación' (hasta 5 pts adicionales) se medirá por la incorporación de tecnologías emergentes que aporten valor agregado.",
    justificacion_legal: "La selección objetiva requiere que los criterios de evaluación y sus puntajes estén claramente definidos. No detallar los sub-criterios de 'Calidad Técnica' introduce un elemento de subjetividad.",
    justificacion_tecnica: "Evita discrecionalidad y facilita la preparación de ofertas competitivas.",
    consecuencia_estimada: "Riesgo de impugnaciones por subjetividad.",
  },
  {
    nombre_archivo_normativa: "Ley 1437 de 2011",
    nombre_archivo_documento: "Evaluación Pliego XYZ-2025",
    tipo: 'Irregularidad',
    titulo_incidencia: "Omisión de Procedimiento para Sanciones",
    articulo_o_seccion: "N/A",
    pagina: '4',
    gravedad: 'Baja',
    evidencia: "El incumplimiento de las obligaciones contractuales dará lugar a las multas y sanciones previstas en la Ley y en el contrato.",
    propuesta_procedimiento: "Se debe incluir un apartado que garantice el debido proceso: 'Para la imposición de multas, se seguirá el siguiente procedimiento: 1. Notificación formal al contratista detallando el presunto incumplimiento. 2. Otorgamiento de un plazo de cinco (5) días hábiles para presentar descargos. 3. Emisión de acto administrativo motivado que decide sobre la multa, contra el cual procederán los recursos de ley.'",
    justificacion_legal: "La imposición de multas es un acto administrativo que debe respetar el debido proceso. Omitir el procedimiento para descargos puede viciar de nulidad la sanción.",
    justificacion_tecnica: "Brinda seguridad jurídica a las partes.",
    consecuencia_estimada: "Posibles nulidades en la imposición de sanciones.",
  },
];


export const mockData: Partial<ValidateDocumentOutput> = {
  documentTitle: "Evaluación Pliego XYZ-2025",
  isRelevantDocument: true,
  relevancyReasoning: "",
  findings: findings,
  complianceScore: 55,
  legalRiskScore: 45,
  scoringBreakdown: {
    totalFindings: 5,
    criticalFindings: 2,
    totalPenalty: 45,
    penaltiesByGravity: {
      Alta: { count: 2, penalty: 25 },
      Media: { count: 1, penalty: 15 },
      Baja: { count: 2, penalty: 5 },
    },
  },
  riskCategory: {
    category: 'HIGH',
    label: 'Alto',
    color: 'orange',
    description: 'El documento tiene problemas significativos que requieren atención',
  },
};
